logging:
  level:
    org:
      springframework:
        security: info

spring:
  datasource:
    password: db-password
    username: db-username
    url: jdbc:postgresql://localhost:5432/exambyte
  application:
    name: ExamByte
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: client-id-here
            client-secret: client-secret-here
            scope: read:public_repo
